name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  CUDA_VERSION: '12.9.0'

jobs:
  build:
    runs-on: windows-2022
    
    strategy:
      matrix:
        include:
          - name: "Windows-x64-Release"
            architecture: x64
            build_config: Release

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup CUDA
      uses: Jimver/cuda-toolkit@v0.2.24
      id: cuda-toolkit
      with:
        cuda: ${{ env.CUDA_VERSION }}
        method: 'local'
        log-file-suffix: 'win-64.txt'

    - name: Setup MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: ${{ matrix.architecture }}

    - name: Configure CMake
      run: |
        cmake --preset=windows-release
      shell: powershell

    - name: Build
      run: cmake --build build/windows-release --config ${{ matrix.build_config }}
      shell: powershell

    - name: Package build artifacts
      shell: pwsh
      run: |
        Write-Host "Packaging build artifacts for GPU testing..."
        New-Item -ItemType Directory -Force -Path artifacts
        Copy-Item -Path "build/windows-release/*" -Destination artifacts/ -Recurse -Force
        Compress-Archive -Path artifacts/* -DestinationPath cuda-build-${{ github.sha }}.zip
        Write-Host "Build artifacts packaged successfully"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: cuda-build-${{ github.sha }}
        path: cuda-build-${{ github.sha }}.zip
        retention-days: 7
        if-no-files-found: error